 # Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  dotnet-commands:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
        - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
        - checkout
        - run:
            name: Restore
            command: dotnet restore .\\Source\\ArchECSStride\\Doprez.Stride.Arch\\Doprez.Stride.Arch.sln
        - run: 
            name: Build
            command: dotnet build .\\Source\\ArchECSStride\\Doprez.Stride.Arch\\Doprez.Stride.Arch.sln
        - run: 
            name: Package
            command: dotnet pack .\\Source\\ArchECSStride\\Doprez.Stride.Arch\\Doprez.Stride.Arch.sln -o ./App
        - run:
            name: Publish
            command: cd App && ls && dotnet nuget push Doprez.Stride.*.nupkg --api-key $NUGET_KEY --source https://api.nuget.org/v3/index.json

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  run-jobs-workflow:
    jobs:
      - dotnet-commands:
          filters:
            branches:
              only:
                - release